DRAFT: Fix API page creation
lakekeeper/lakekeeper pull request #691
Opened 2024-12-19 05:52 UTC by bitsondatadev

Here's the current two options. I wanted to share progress at least.

mkdocs plugin
![mkdocs-plugin](https://github.com/user-attachments/assets/532f1a9f-9e8d-4c04-913b-5f73de14509f)

redocly
![redocly](https://github.com/user-attachments/assets/cae40839-4bd8-4492-905a-818cc1d2994c)

2024-12-19 08:32 UTC, c-thiel commented
Both looking much better than what we had before!
Any preference from your side?

Could you change the following paths to the new locations as well?:

- In the rust crate, you can see it here in the failing test: https://github.com/lakekeeper/lakekeeper/actions/runs/12407088250/job/34636544730?pr=691
- In the main just file that re-creates the openapi specs (update-openfga, update-management-openapi, add-return-uuid-to-rest-openapi)
- In `.github/unittests.yaml` where we validate that the openapi spec is up-to-date and try to generate the UI client from it. 


I believe after that tests should start working again

2025-02-03 11:32 UTC, c-thiel requested changes

2025-02-03 11:32 UTC, c-thiel commented on site/mkdocs.yml
> +  custom_dir: overrides
The overrides dir is missing in this PR - serve fails with:
```
ERROR   -  Config value 'theme': The path set in custom_dir ('/Users/cht/code/ht/iceberg-rest/iceberg-catalog/site/overrides')
           does not exist.
```

2025-02-03 18:31 UTC, bitsondatadev commented on site/mkdocs.yml
> +  custom_dir: overrides
Ah yip...removed the only file inside the directory that I was toying with and ergo removed the directory from GitHub. I'll remove this for now. Likely will be added later when Muna does his magic.

2025-02-03 18:35 UTC, bitsondatadev commented on site/mkdocs.yml
> -    - navigation.path
This is an [MkDocs Material Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) feature. Removing it to avoid confusion.

2025-02-04 07:33 UTC, c-thiel submitted a review, later dismissed

2025-02-04 07:37 UTC, c-thiel approved these changes

2025-02-05 12:42 UTC, merged